[build]
  command   = "cd frontend && npm install && npm run build"
  functions = "netlify/functions"
  publish   = "frontend/build"

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/api/:splat"
  status = 200
  force = true